In [ ]:
#PSL Pakistan Super League

In [ ]:
# 1- problem identify / problem define
# 2- data collection (different sources)
# 3- data understanding
# 4- data processing
# 5- Feature Engineering
# 6- Training & Spliting --- 80% data for training and 20% data for testing
#  * randomness
#  * confusion matrix
#  * precision
#  * accuracy
#  * support
#  * f1 score
#  * cross validation
# It cross check features,colour,shape,price
# What are transformers and LLM?

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
from google.colab import files
uploaded= files.upload()

Saving PSL.csv to PSL.csv

In [ ]:
df= pd.read_csv('PSL.csv')

/tmp/ipykernel_2571/2282526829.py:1: DtypeWarning: Columns (24,51,52,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('PSL.csv')

In [ ]:
df.head()

,Unnamed: 0,Team,Over Number,Ball Number,Batter,Bowler,Non Striker,Batter runs,runs.extras,Byes,...,Outcome_by_wickets,Replacement,Replacement (in),Replacement (out),Replacement reason,Replacement role,Sub (in),Sub (out),Sub team,Sub reason
0,0,Lahore Qalandars,1,1,Fakhar Zaman,Imad Wasim,Gauhar Ali,1,0,0,...,5,0,0,0.0,0,0,0,0,0,0
1,1,Lahore Qalandars,1,2,Gauhar Ali,Imad Wasim,Fakhar Zaman,4,0,0,...,5,0,0,0.0,0,0,0,0,0,0
2,2,Lahore Qalandars,1,3,Gauhar Ali,Imad Wasim,Fakhar Zaman,0,0,0,...,5,0,0,0.0,0,0,0,0,0,0
3,3,Lahore Qalandars,1,4,Haris Sohail,Imad Wasim,Fakhar Zaman,1,0,0,...,5,0,0,0.0,0,0,0,0,0,0
4,4,Lahore Qalandars,1,5,Fakhar Zaman,Imad Wasim,Haris Sohail,0,0,0,...,5,0,0,0.0,0,0,0,0,0,0

In [ ]:
df.columns

Index(['Unnamed: 0', 'Team', 'Over Number', 'Ball Number', 'Batter', 'Bowler',
       'Non Striker', 'Batter runs', 'runs.extras', 'Byes', 'Legbyes',
       'Noballs', 'Penalty', 'Wides', 'NonBoundry runs', 'Total Runs',
       'Wickets', 'Wicket Type', 'Fielders for wicket', 'Player Out',
       'Review By', 'Batter review', 'Review Decision', 'Review umpire',
       'Review type', 'Review umpire_call', 'Target Runs', 'Target overs',
       'dates', 'Match Type', 'Gender', 'Overs', 'venue', 'season',
       'event match_number', 'Toss Decision', 'Official Umpires', 'Opposition',
       'Team Type', 'Team A players', 'Team B players', 'Toss Winner',
       'Winner', 'MOTM', 'Outcome_by_runs', 'Outcome_by_wickets',
       'Replacement', 'Replacement (in)', 'Replacement (out)',
       'Replacement reason', 'Replacement role', 'Sub (in)', 'Sub (out)',
       'Sub team', 'Sub reason'],
      dtype='object')

In [ ]:
df['Over Number'].min()

1

In [ ]:
df.describe()

,Unnamed: 0,Over Number,Ball Number,Batter runs,runs.extras,Byes,Legbyes,Noballs,Penalty,Wides,...,Review umpire_call,Target Runs,Target overs,Overs,event match_number,Toss Decision,Outcome_by_runs,Outcome_by_wickets,Replacement,Replacement (out)
count,59560.000000,59560.000000,59560.000000,59560.000000,59560.000000,59560.000000,59560.000000,59560.000000,59560.000000,59560.000000,...,59560.0,28843.000000,28843.000000,59560.0,51968.000000,0.0,59560.000000,59560.000000,59560.000000,59545.0
mean,29779.500000,10.123254,3.615883,1.275151,0.069258,0.006145,0.022011,0.004030,0.000084,0.036988,...,0.0,166.804875,19.727178,20.0,14.354430,NaN,13.958009,3.165497,0.000252,0.0
std,17193.635353,5.650184,1.810616,1.652559,0.356496,0.135514,0.204474,0.065948,0.020488,0.253173,...,0.0,34.663461,1.935043,0.0,8.582013,NaN,23.678372,3.237509,0.015868,0.0
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,20.0,1.000000,NaN,0.000000,0.000000,0.000000,0.0
25%,14889.750000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,148.000000,20.000000,20.0,7.000000,NaN,0.000000,0.000000,0.000000,0.0
50%,29779.500000,10.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,171.000000,20.000000,20.0,14.000000,NaN,0.000000,3.000000,0.000000,0.0
75%,44669.250000,15.000000,5.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,188.000000,20.000000,20.0,21.000000,NaN,21.000000,6.000000,0.000000,0.0
max,59559.000000,20.000000,11.000000,6.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,0.0,263.000000,20.000000,20.0,30.000000,NaN,119.000000,10.000000,1.000000,0.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59560 entries, 0 to 59559
Data columns (total 55 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           59560 non-null  int64
 1   Team                 59560 non-null  object
 2   Over Number          59560 non-null  int64
 3   Ball Number          59560 non-null  int64
 4   Batter               59560 non-null  object
 5   Bowler               59560 non-null  object
 6   Non Striker          59560 non-null  object
 7   Batter runs          59560 non-null  int64
 8   runs.extras          59560 non-null  int64
 9   Byes                 59560 non-null  int64
 10  Legbyes              59560 non-null  int64
 11  Noballs              59560 non-null  int64
 12  Penalty              59560 non-null  int64
 13  Wides                59560 non-null  int64
 14  NonBoundry runs      59540 non-null  object
 15  Total Runs           59560 non-null  int64
 16  Wickets              59560 non-null  int64
 17  Wicket Type          59560 non-null  object
 18  Fielders for wicket  59560 non-null  object
 19  Player Out           59560 non-null  object
 20  Review By            57501 non-null  object
 21  Batter review        57501 non-null  object
 22  Review Decision      57501 non-null  object
 23  Review umpire        57644 non-null  object
 24  Review type          59495 non-null  object
 25  Review umpire_call   59560 non-null  int64
 26  Target Runs          28843 non-null  float64
 27  Target overs         28843 non-null  float64
 28  dates                59560 non-null  object
 29  Match Type           59560 non-null  object
 30  Gender               59560 non-null  object
 31  Overs                59560 non-null  int64
 32  venue                59560 non-null  object
 33  season               59560 non-null  object
 34  event match_number   51968 non-null  float64
 35  Toss Decision        0 non-null      float64
 36  Official Umpires     59560 non-null  object
 37  Opposition           59560 non-null  object
 38  Team Type            59560 non-null  object
 39  Team A players       59560 non-null  object
 40  Team B players       59560 non-null  object
 41  Toss Winner          59560 non-null  object
 42  Winner               58326 non-null  object
 43  MOTM                 59137 non-null  object
 44  Outcome_by_runs      59560 non-null  int64
 45  Outcome_by_wickets   59560 non-null  int64
 46  Replacement          59560 non-null  int64
 47  Replacement (in)     59560 non-null  object
 48  Replacement (out)    59545 non-null  float64
 49  Replacement reason   59560 non-null  object
 50  Replacement role     59560 non-null  object
 51  Sub (in)             59560 non-null  object
 52  Sub (out)            59560 non-null  object
 53  Sub team             59560 non-null  object
 54  Sub reason           59560 non-null  object
dtypes: float64(5), int64(17), object(33)
memory usage: 25.0+ MB

In [ ]:
df.isnull().sum()

Unnamed: 0                 0
Team                       0
Over Number                0
Ball Number                0
Batter                     0
Bowler                     0
Non Striker                0
Batter runs                0
runs.extras                0
Byes                       0
Legbyes                    0
Noballs                    0
Penalty                    0
Wides                      0
NonBoundry runs           20
Total Runs                 0
Wickets                    0
Wicket Type                0
Fielders for wicket        0
Player Out                 0
Review By               2059
Batter review           2059
Review Decision         2059
Review umpire           1916
Review type               65
Review umpire_call         0
Target Runs            30717
Target overs           30717
dates                      0
Match Type                 0
Gender                     0
Overs                      0
venue                      0
season                     0
event match_number      7592
Toss Decision          59560
Official Umpires           0
Opposition                 0
Team Type                  0
Team A players             0
Team B players             0
Toss Winner                0
Winner                  1234
MOTM                     423
Outcome_by_runs            0
Outcome_by_wickets         0
Replacement                0
Replacement (in)           0
Replacement (out)         15
Replacement reason         0
Replacement role           0
Sub (in)                   0
Sub (out)                  0
Sub team                   0
Sub reason                 0
dtype: int64

In [ ]:
df.dropna()

Empty DataFrame
Columns: [Unnamed: 0, Team, Over Number, Ball Number, Batter, Bowler, Non Striker, Batter runs, runs.extras, Byes, Legbyes, Noballs, Penalty, Wides, NonBoundry runs, Total Runs, Wickets, Wicket Type, Fielders for wicket, Player Out, Review By, Batter review, Review Decision, Review umpire, Review type, Review umpire_call, Target Runs, Target overs, dates, Match Type, Gender, Overs, venue, season, event match_number, Toss Decision, Official Umpires, Opposition, Team Type, Team A players, Team B players, Toss Winner, Winner, MOTM, Outcome_by_runs, Outcome_by_wickets, Replacement, Replacement (in), Replacement (out), Replacement reason, Replacement role, Sub (in), Sub (out), Sub team, Sub reason]
Index: []

[0 rows x 55 columns]

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [ ]:
df.shape

(59560, 55)

In [ ]:
print(df.columns.tolist())

['Unnamed: 0', 'Team', 'Over Number', 'Ball Number', 'Batter', 'Bowler', 'Non Striker', 'Batter runs', 'runs.extras', 'Byes', 'Legbyes', 'Noballs', 'Penalty', 'Wides', 'NonBoundry runs', 'Total Runs', 'Wickets', 'Wicket Type', 'Fielders for wicket', 'Player Out', 'Review By', 'Batter review', 'Review Decision', 'Review umpire', 'Review type', 'Review umpire_call', 'Target Runs', 'Target overs', 'dates', 'Match Type', 'Gender', 'Overs', 'venue', 'season', 'event match_number', 'Toss Decision', 'Official Umpires', 'Opposition', 'Team Type', 'Team A players', 'Team B players', 'Toss Winner', 'Winner', 'MOTM', 'Outcome_by_runs', 'Outcome_by_wickets', 'Replacement', 'Replacement (in)', 'Replacement (out)', 'Replacement reason', 'Replacement role', 'Sub (in)', 'Sub (out)', 'Sub team', 'Sub reason']